/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modele.*;

import utils.FieldFiller;
import utils.Utilitaire;

/**
 *
 * @author 1795511
 */
public class GuiPrincipal extends javax.swing.JFrame {
    private ArrayList<Hangar> mesHangars;
    private ArrayList<Baux> mesBaux;
    private ArrayList<Avion> mesAvions;
    private ArrayList<ModeleAvion> mesModeleAvion;
    private ArrayList<Client>mesClients;
    private double[] mesPrix;
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal(ArrayList<Hangar> mesHangars, ArrayList<Baux> mesBaux, ArrayList<Avion> mesAvions, ArrayList<ModeleAvion> mesModeleAvion,
            ArrayList<Client>mesClients, double[] mesPrix) {
        initComponents();
        this.mesHangars = mesHangars;
        this.mesBaux = mesBaux;
        this.mesAvions = mesAvions;
        this.mesModeleAvion = mesModeleAvion;
        this.mesClients=mesClients;
        this.mesPrix = mesPrix;
        comboBoxClient.setRenderer(new ClientRenderer());
        comboBoxModeleAvion.setRenderer(new ModeleAvionRenderer());
        comboBoxHangar1.setRenderer(new HangarRenderer());
        comboBoxHangar2.setRenderer(new HangarRenderer());
        comboBoxChoixHangar.setRenderer(new HangarRenderer());
        FieldFiller.comboBoxFiller(comboBoxClient, mesClients);
        FieldFiller.comboBoxFiller(comboBoxModeleAvion, mesModeleAvion);
        FieldFiller.comboBoxFiller(comboBoxHangar1, mesHangars);
        FieldFiller.comboBoxFiller(comboBoxHangar2, mesHangars);
        FieldFiller.comboBoxFiller(comboBoxChoixHangar, mesHangars);
        System.out.println(mesHangars.get(0));
        comboBoxHangar1.setSelectedItem(mesHangars.get(0));
        comboBoxHangar2.setSelectedItem(mesHangars.get(1));
        Hangar hangar1 = (Hangar) comboBoxHangar1.getSelectedItem();
        FieldFiller.tableHangarFiller((DefaultTableModel) tableHangar1.getModel(), hangar1.getMesAvions());
        Hangar hangar2 = (Hangar) comboBoxHangar2.getSelectedItem();
        FieldFiller.tableHangarFiller((DefaultTableModel) tableHangar2.getModel(), hangar2.getMesAvions());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNbAvion1 = new javax.swing.JLabel();
        txtNbAvion1 = new javax.swing.JTextField();
        lblTotalLoc1 = new javax.swing.JLabel();
        txtTotalLocation1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSuperficieDispo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHangar1 = new javax.swing.JTable();
        comboBoxHangar1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblNbAvion2 = new javax.swing.JLabel();
        txtNbAvion2 = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        txtTotalLocation2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSuperficieDispo2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHangar2 = new javax.swing.JTable();
        comboBoxHangar2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblBail = new javax.swing.JLabel();
        lblImmatriculation = new javax.swing.JLabel();
        txtImmatriculation = new javax.swing.JTextField();
        comboBoxModeleAvion = new javax.swing.JComboBox<>();
        lblDureeContrat = new javax.swing.JLabel();
        txtDureeContrat = new javax.swing.JTextField();
        btnAnnulerBail = new javax.swing.JButton();
        btnConfirmer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboBoxClient = new javax.swing.JComboBox<>();
        comboBoxChoixHangar = new javax.swing.JComboBox<>();
        btnNouveauClient = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrixContrat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNbAvion1.setText("nombre avion:");
        lblNbAvion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNbAvion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNbAvion1.setEnabled(false);

        lblTotalLoc1.setText("Total location:");
        lblTotalLoc1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTotalLocation1.setEnabled(false);

        jLabel5.setText("Superficie disponible:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSuperficieDispo1.setEnabled(false);

        jLabel6.setText("pi2");

        jScrollPane2.setAutoscrolls(true);

        tableHangar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Avion", "Modele", "Superficie", "Nom, Prenom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableHangar1);

        comboBoxHangar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxHangar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHangar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(comboBoxHangar1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(txtSuperficieDispo1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNbAvion1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNbAvion1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTotalLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTotalLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(comboBoxHangar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSuperficieDispo1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbAvion1)
                    .addComponent(txtNbAvion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalLoc1)
                    .addComponent(txtTotalLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNbAvion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNbAvion2.setText("Nombre avion:");
        lblNbAvion2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNbAvion2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNbAvion2.setEnabled(false);

        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Total location:");
        lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTotalLocation2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalLocation2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTotalLocation2.setEnabled(false);

        jLabel7.setText("Superficie disponible:");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSuperficieDispo2.setEnabled(false);

        jLabel8.setText("pi2");

        jScrollPane1.setAutoscrolls(true);

        tableHangar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Avion", "Modele", "Superficie", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHangar2.setEnabled(false);
        jScrollPane1.setViewportView(tableHangar2);

        comboBoxHangar2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxHangar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHangar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboBoxHangar2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSuperficieDispo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNbAvion2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNbAvion2)
                                    .addComponent(txtTotalLocation2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(comboBoxHangar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSuperficieDispo2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbAvion2)
                    .addComponent(txtNbAvion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(txtTotalLocation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBail.setText("Nouveau Contrat");
        lblBail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImmatriculation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImmatriculation.setText("Immatriculation");
        lblImmatriculation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtImmatriculation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxModeleAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxModeleAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModeleAvionActionPerformed(evt);
            }
        });

        lblDureeContrat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDureeContrat.setText("Durée du contrat :");
        lblDureeContrat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDureeContrat.setText("0");
        txtDureeContrat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDureeContratKeyReleased(evt);
            }
        });

        btnAnnulerBail.setText("Annuler");
        btnAnnulerBail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAnnulerBail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerBailActionPerformed(evt);
            }
        });

        btnConfirmer.setText("Confirmer");
        btnConfirmer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmerActionPerformed(evt);
            }
        });

        jLabel3.setText("jour(s)");

        comboBoxClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxChoixHangar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNouveauClient.setText("Nouveau client");
        btnNouveauClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauClientActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Client");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Modele d'avion");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Hangar");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Prix de la location :");

        txtPrixContrat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrixContratKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblBail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxModeleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboBoxChoixHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnnulerBail, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblDureeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDureeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrixContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNouveauClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImmatriculation)
                    .addComponent(txtImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxModeleAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxChoixHangar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDureeContrat)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(txtPrixContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDureeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnulerBail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXECUTIVE FLIGTH SERVICES");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouveauClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauClientActionPerformed
        GuiNouveauClient newClient = new GuiNouveauClient(mesClients,comboBoxClient);
        newClient.setVisible(true);
    }//GEN-LAST:event_btnNouveauClientActionPerformed

    private void btnAnnulerBailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerBailActionPerformed
        txtDureeContrat.setText("0");
        txtImmatriculation.setText("");
        comboBoxModeleAvion.setSelectedIndex(0);
        comboBoxClient.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnAnnulerBailActionPerformed

    private void btnConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmerActionPerformed
        String champs = "Veuillez remplir les choix suivants: ";
        boolean plein = true;
        if("".equals(txtImmatriculation.getText()) || txtImmatriculation.getText() == null){
            plein = false;
            champs = champs + "\nImmatriculation";
        }
        
        if(comboBoxClient.getSelectedIndex() == 0){
            plein = false;
            champs = champs + "\nClient";
        }

        if(comboBoxModeleAvion.getSelectedIndex() == 0){
            plein = false;
            champs = champs + "\nModèle d'avion";
        }
        
        if(comboBoxChoixHangar.getSelectedIndex() == 0){
            plein = false;
            champs = champs + "\nHangar";
        }
        
        if("".equals(txtDureeContrat.getText()) || txtDureeContrat.getText() == null || "0".equals(txtDureeContrat.getText())){           
            plein = false;
            champs = champs + "\nDurée de contrat";
        }
        
        if(plein == false){
            JOptionPane.showMessageDialog(null, champs);
            return;
        }

        Hangar hangar = (Hangar) comboBoxChoixHangar.getSelectedItem();
        Avion avion = new Avion(mesAvions.size() + 1, (ModeleAvion) comboBoxModeleAvion.getSelectedItem(), (Client) comboBoxClient.getSelectedItem(), (Hangar) comboBoxChoixHangar.getSelectedItem());
        Client leClient = (Client) comboBoxClient.getSelectedItem();
        System.out.println(hangar.calculerSuperficieRestante());
        System.out.println(avion.getModele().getSuperficie());
        if(hangar.calculerSuperficieRestante() < avion.getModele().getSuperficie()){
            JOptionPane.showMessageDialog(null,"Le hangar choisi n'a pas assez d'espace pour acceuillir le nouvel avion, veuillez en choisir un autre.");
            return;
        }
        
        String messageSauvegarde = "Veuillez valider les informations et cliquer sur OK pour sauvegarder." + "\nImmatriculation : " + txtImmatriculation.getText()
                                    + "\nClient : " + leClient.getNom() + " " + leClient.getPrenom()
                                    + "\nModele d'avion : " + avion.getModele().getModele()
                                    + "\nHangar : " + hangar.getIdHangar()
                                    + "\nDurée du bail : " + txtDureeContrat.getText() + " jour(s)";
        int input = JOptionPane.showConfirmDialog(null, messageSauvegarde, "Nouveau bail",
				JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(input == 2){
            return;
        }
        
        mesAvions.add(avion);
        hangar.ajouterAvion(avion);
        mesBaux.add(new Baux(mesBaux.size() + 1, Integer.parseInt(txtDureeContrat.getText()), (Client) comboBoxClient.getSelectedItem(), avion, Double.parseDouble(txtPrixContrat.getText())));
        avion.setMonBail(mesBaux.get(mesBaux.size()-1));
        Hangar hangar1 = (Hangar) comboBoxHangar1.getSelectedItem();
        FieldFiller.tableHangarFiller((DefaultTableModel) tableHangar1.getModel(), hangar1.getMesAvions());
        Hangar hangar2 = (Hangar) comboBoxHangar2.getSelectedItem();
        FieldFiller.tableHangarFiller((DefaultTableModel) tableHangar2.getModel(), hangar2.getMesAvions());
        if(hangar == comboBoxHangar1.getSelectedItem()){
            FieldFiller.labelFiller(hangar, txtTotalLocation1, txtSuperficieDispo1, txtNbAvion1, tableHangar1);
            
        }else if(hangar == comboBoxHangar2.getSelectedItem()){
            FieldFiller.labelFiller(hangar, txtTotalLocation2, txtSuperficieDispo2, txtNbAvion2, tableHangar2);
            
        }
        
        JOptionPane.showMessageDialog(null,"Bail enregistré");
//        try {
//            ManipulationFichier.sauvegardeListeObjet("Baux.dat", mesBaux);
//            ManipulationFichier.sauvegardeListeObjet("Avion.dat", mesAvions);
//        } catch (IOException ex) {
//            System.out.println("Erreur de sauvegarde");
//        }
    }//GEN-LAST:event_btnConfirmerActionPerformed

    private void comboBoxHangar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHangar1ActionPerformed
        if(comboBoxHangar1.getSelectedItem() != "" && comboBoxHangar1.getSelectedItem() != null && comboBoxHangar1.getSelectedIndex() != 0){
            Hangar h = (Hangar) comboBoxHangar1.getSelectedItem();
            FieldFiller.labelFiller(h, txtTotalLocation1, txtSuperficieDispo1, txtNbAvion1, tableHangar1);
        }else if(comboBoxHangar1.getSelectedItem() == "" || comboBoxHangar1.getSelectedIndex() == 0){
            txtNbAvion1.setText("");
            txtTotalLocation1.setText("");
            txtSuperficieDispo1.setText("");
        }
    }//GEN-LAST:event_comboBoxHangar1ActionPerformed

    private void comboBoxHangar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHangar2ActionPerformed
        if(comboBoxHangar2.getSelectedItem() != "" && comboBoxHangar2.getSelectedItem() != null && comboBoxHangar2.getSelectedIndex() != 0){
            Hangar h = (Hangar) comboBoxHangar2.getSelectedItem();
            FieldFiller.labelFiller(h, txtTotalLocation2, txtSuperficieDispo2, txtNbAvion2, tableHangar2);
        }else if(comboBoxHangar2.getSelectedItem() == "" || comboBoxHangar2.getSelectedIndex() == 0){
            txtNbAvion2.setText("");
            txtTotalLocation2.setText("");
            txtSuperficieDispo2.setText("");
        }
    }//GEN-LAST:event_comboBoxHangar2ActionPerformed

    private void comboBoxModeleAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModeleAvionActionPerformed
        int o = comboBoxModeleAvion.getSelectedIndex();
        System.out.println(comboBoxModeleAvion.getSelectedItem());
        System.out.println(comboBoxModeleAvion.getSelectedIndex());
        if(comboBoxModeleAvion.getSelectedIndex() > 0){
            if(!("".equals(txtDureeContrat.getText()))){
                ModeleAvion leModelAvion = (ModeleAvion) comboBoxModeleAvion.getSelectedItem();
                txtPrixContrat.setText(String.valueOf(Utilitaire.calculerTarifLocation(leModelAvion.getSuperficie(), Integer.parseInt(txtDureeContrat.getText()), mesPrix)));
            }else{
                txtPrixContrat.setText("0.00");
            }
        }else if(comboBoxModeleAvion.getSelectedIndex()== 0){
            txtPrixContrat.setText("0.00");
        }
        
    }//GEN-LAST:event_comboBoxModeleAvionActionPerformed

    private void txtPrixContratKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrixContratKeyTyped
        if(comboBoxModeleAvion.getSelectedIndex() > 0){
            ModeleAvion leModelAvion = (ModeleAvion) comboBoxModeleAvion.getSelectedItem();
            txtPrixContrat.setText(String.valueOf(Utilitaire.calculerTarifLocation(leModelAvion.getSuperficie(), Integer.parseInt(txtDureeContrat.getText()), mesPrix)));
            
        }
    }//GEN-LAST:event_txtPrixContratKeyTyped

    
    /**
     * Cette méthode affiche et calcule le tarif de location
     * Si la durée n'est pas = à ""
     * @param evt évenement 
     */
    private void txtDureeContratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDureeContratKeyReleased
        System.out.println(txtDureeContrat.getText());
        if(!("".equals(txtDureeContrat.getText()))){
            if(comboBoxModeleAvion.getSelectedIndex() > 0){
            ModeleAvion leModelAvion = (ModeleAvion) comboBoxModeleAvion.getSelectedItem();
            txtPrixContrat.setText(String.valueOf(Utilitaire.calculerTarifLocation(leModelAvion.getSuperficie(), Integer.parseInt(txtDureeContrat.getText()), mesPrix)));     
            }
        }      
    }//GEN-LAST:event_txtDureeContratKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulerBail;
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnNouveauClient;
    private javax.swing.JComboBox<String> comboBoxChoixHangar;
    private javax.swing.JComboBox<String> comboBoxClient;
    private javax.swing.JComboBox<String> comboBoxHangar1;
    private javax.swing.JComboBox<String> comboBoxHangar2;
    private javax.swing.JComboBox<String> comboBoxModeleAvion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblBail;
    private javax.swing.JLabel lblDureeContrat;
    private javax.swing.JLabel lblImmatriculation;
    private javax.swing.JLabel lblNbAvion1;
    private javax.swing.JLabel lblNbAvion2;
    private javax.swing.JLabel lblTotalLoc1;
    private javax.swing.JTable tableHangar1;
    private javax.swing.JTable tableHangar2;
    private javax.swing.JTextField txtDureeContrat;
    private javax.swing.JTextField txtImmatriculation;
    private javax.swing.JTextField txtNbAvion1;
    private javax.swing.JTextField txtNbAvion2;
    private javax.swing.JTextField txtPrixContrat;
    private javax.swing.JTextField txtSuperficieDispo1;
    private javax.swing.JTextField txtSuperficieDispo2;
    private javax.swing.JTextField txtTotalLocation1;
    private javax.swing.JTextField txtTotalLocation2;
    // End of variables declaration//GEN-END:variables
}
